version: 2
checks:
  identical-code:
    config:
      threshold: 150
  similar-code:
    config:
      threshold: 200
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 35
plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      extensions:
        - .es11
        - .js
        - .jsx
        - .ts
        - .tsx
      file: .eslintrc.js
exclude_patterns:
  - 'node_modules/'
